// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("order_tracking")]
	public class OrderTracking
	{
		[Column("tracking_id", IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int             TrackingId { get; set; } // integer
		[Column("order_id"                                                                                      )] public int             OrderId    { get; set; } // integer
		[Column("status"     , CanBeNull    = false                                                             )] public string          Status     { get; set; } = null!; // character varying(50)
		[Column("changed_at"                                                                                    )] public DateTimeOffset? ChangedAt  { get; set; } // timestamp (6) with time zone
		[Column("changed_by"                                                                                    )] public int?            ChangedBy  { get; set; } // integer
		[Column("notes"                                                                                         )] public string?         Notes      { get; set; } // text

		#region Associations
		/// <summary>
		/// FK_order_id
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(OrderId), OtherKey = nameof(DataModel.Order.OrderId))]
		public Order Order { get; set; } = null!;

		/// <summary>
		/// FK_user_id
		/// </summary>
		[Association(ThisKey = nameof(ChangedBy), OtherKey = nameof(User.UserId))]
		public User? Userid { get; set; }
		#endregion
	}
}
