version: '3.8'

services:
  backend:
    build:
      context: ./backend/backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - uleats_db_data:/var/opt/mssql

volumes:
  uleats_db_data: