// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("customers")]
	public class Customer
	{
		[Column("customer_id", IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int    CustomerId { get; set; } // integer
		[Column("address"    , CanBeNull    = false                                                             )] public string Address    { get; set; } = null!; // text
		[Column("user_id"                                                                                       )] public int    UserId     { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_customer_id backreference
		/// </summary>
		[Association(ThisKey = nameof(CustomerId), OtherKey = nameof(OrderItem.CustomerId))]
		public IEnumerable<OrderItem> OrderItems { get; set; } = null!;

		/// <summary>
		/// USER_ID
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.UserId))]
		public User User { get; set; } = null!;
		#endregion
	}
}
