// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("delivery")]
	public class Delivery
	{
		[Column("delivery_id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     DeliveryId   { get; set; } // integer
		[Column("vehicle_plate"                                                                                  )] public string? VehiclePlate { get; set; } // character varying(20)
		[Column("phone"                                                                                          )] public string? Phone        { get; set; } // character varying(50)
		[Column("vehicle_type"                                                                                   )] public string? VehicleType  { get; set; } // character varying(10)
		[Column("user_id"                                                                                        )] public int     UserId       { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_delivery_id backreference
		/// </summary>
		[Association(ThisKey = nameof(DeliveryId), OtherKey = nameof(Order.DeliveryId))]
		public IEnumerable<Order> Orders { get; set; } = null!;

		/// <summary>
		/// FK_user_id
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.UserId))]
		public User User { get; set; } = null!;
		#endregion
	}
}
