// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("payments")]
	public class Payment
	{
		[Column("payment_id"    , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int             PaymentId     { get; set; } // integer
		[Column("order_id"                                                                                         )] public int             OrderId       { get; set; } // integer
		[Column("amount"                                                                                           )] public decimal         Amount        { get; set; } // numeric(10,2)
		[Column("payment_method", CanBeNull    = false                                                             )] public string          PaymentMethod { get; set; } = null!; // character varying(20)
		[Column("payment_status", CanBeNull    = false                                                             )] public string          PaymentStatus { get; set; } = null!; // character varying(20)
		[Column("transaction_id"                                                                                   )] public string?         TransactionId { get; set; } // character varying(100)
		[Column("payment_day"                                                                                      )] public DateTimeOffset? PaymentDay    { get; set; } // timestamp (6) with time zone

		#region Associations
		/// <summary>
		/// FK_order_id
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(OrderId), OtherKey = nameof(DataModel.Order.OrderId))]
		public Order Order { get; set; } = null!;
		#endregion
	}
}
