// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("restaurant")]
	public class Restaurant
	{
		[Column("restaurant_id", IsPrimaryKey = true )] public int     RestaurantId { get; set; } // integer
		[Column("name"         , CanBeNull    = false)] public string  Name         { get; set; } = null!; // character varying(100)
		[Column("address"      , CanBeNull    = false)] public string  Address      { get; set; } = null!; // text
		[Column("phone"                              )] public string? Phone        { get; set; } // character varying(20)
		[Column("user_id"                            )] public int?    UserId       { get; set; } // integer
		[Column("description"                        )] public string? Description  { get; set; } // text
		[Column("logo_url"                           )] public string? LogoUrl      { get; set; } // character varying(255)

		#region Associations
		/// <summary>
		/// FK_restaurant_id backreference
		/// </summary>
		[Association(ThisKey = nameof(RestaurantId), OtherKey = nameof(Product.RestaurantId))]
		public IEnumerable<Product> Products { get; set; } = null!;

		/// <summary>
		/// FK_restaurant_id backreference
		/// </summary>
		[Association(ThisKey = nameof(RestaurantId), OtherKey = nameof(Order.RestaurantId))]
		public IEnumerable<Order> Orders { get; set; } = null!;

		/// <summary>
		/// Restaurant_user_id
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.UserId))]
		public User? User { get; set; }
		#endregion
	}
}
