// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("user")]
	public class User
	{
		[Column("user_id"   , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     UserId    { get; set; } // integer
		[Column("email"     , CanBeNull    = false                                                             )] public string  Email     { get; set; } = null!; // character varying(100)
		[Column("password"  , CanBeNull    = false                                                             )] public string  Password  { get; set; } = null!; // character varying(100)
		[Column("first_name", CanBeNull    = false                                                             )] public string  FirstName { get; set; } = null!; // character varying(50)
		[Column("last_name" , CanBeNull    = false                                                             )] public string  LastName  { get; set; } = null!; // character varying(50)
		[Column("phone"                                                                                        )] public string? Phone     { get; set; } // character varying(20)
		[Column("user_type" , CanBeNull    = false                                                             )] public string  UserType  { get; set; } = null!; // character varying(20)

		#region Associations
		/// <summary>
		/// FK_user_id backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(Delivery.UserId))]
		public IEnumerable<Delivery> Deliveries { get; set; } = null!;

		/// <summary>
		/// FK_user_id backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(OrderTracking.ChangedBy))]
		public IEnumerable<OrderTracking> OrderTrackings { get; set; } = null!;

		/// <summary>
		/// Restaurant_user_id backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(Restaurant.UserId))]
		public IEnumerable<Restaurant> Restaurants { get; set; } = null!;

		/// <summary>
		/// USER_ID backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(Customer.UserId))]
		public IEnumerable<Customer> Customers { get; set; } = null!;
		#endregion
	}
}
