/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CartDrawer: typeof import('./components/CartDrawer.vue')['default']
    LogIn: typeof import('./components/LogIn.vue')['default']
    LoginButton: typeof import('./components/LoginButton.vue')['default']
    ProductList: typeof import('./components/ProductList.vue')['default']
    RegisterButton: typeof import('./components/RegisterButton.vue')['default']
    RestaurantList: typeof import('./components/RestaurantList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
